spring.application.name=interns-management

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/l3_pfe
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

spring.servlet.multipart.max-file-size=160MB
spring.servlet.multipart.max-request-size=160MB


# Always run initialization scripts regardless of DB type
#spring.sql.init.mode=always 
#
## Optional: Specify locations if not using default names
#spring.sql.init.schema-locations=classpath:schema.sql
#spring.sql.init.data-locations=classpath:data.sql